# 1. Import Libraries

In [16]:
import pandas as pd
import joblib

# 2. Load Model

In [17]:
model = joblib.load(
    'gradient_boosting_tuned.joblib'
)
model
selected_features = joblib.load(
    'selected_features.joblib'
)

# 3. Buat Data Inference

In [18]:
data_inf = pd.DataFrame({
    'name': ['Maruti Swift Dzire'],
    'year': [2018],
    'km_driven': [45000],
    'fuel': ['Diesel'],
    'seller_type': ['Individual'],
    'transmission': ['Manual'],
    'owner': ['First Owner'],
    'mileage(km/ltr/kg)': [22.0],
    'engine': [1248.0],
    'max_power': [74.0],
    'seats': [5.0]
})

data_inf

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire,2018,45000,Diesel,Individual,Manual,First Owner,22.0,1248.0,74.0,5.0

# 4. Feature Engineering

In [19]:
REFERENCE_YEAR = 2020

data_inf['car_age'] = (
    REFERENCE_YEAR
    - data_inf['year']
)

data_inf['brand'] = (
    data_inf['name']
    .str.split()
    .str[0]
)

data_inf = data_inf.drop(
    columns=['name', 'year']
)

data_inf

,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats,car_age,brand
0,45000,Diesel,Individual,Manual,First Owner,22.0,1248.0,74.0,5.0,2,Maruti

In [ ]:
data_inf_final = data_inf[
    selected_features
]
data_inf_final

,km_driven,mileage(km/ltr/kg),engine,max_power,seats,car_age,fuel,seller_type,transmission,owner,brand
0,45000,22.0,1248.0,74.0,5.0,2,Diesel,Individual,Manual,First Owner,Maruti

# 5. Predict

In [ ]:
prediction = model.predict(
    data_inf_final
)
print(
    f'Predicted Selling Price: '
    f'₹{prediction[0]:,.2f}'
)

Predicted Selling Price: ₹708,419.58

#### Inference Conclusion

The trained **Gradient Boosting Regressor** successfully generates a predicted selling price based on the input vehicle characteristics.

This demonstrates that the saved model can be used to perform inference on new, unseen data and provide estimated used car selling prices.